import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import { ChildProps } from "@/types";

const orbitron = Orbitron({
  variable: "--font-orbitron",
  weight: ['400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildProps) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
